apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction
spec:
  selector:
    matchLabels:
      run: prediction
  replicas: 1
  template:
    metadata:
      labels:
        run: prediction
    spec:
      containers:
      - name: prediction
        image: adrik976/udacity-prediction
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
---

apiVersion: v1
kind: Service
metadata:
  name: prediction
  labels:
    run: prediction
spec:
  ports:
  - port: 80
  selector:
    run: prediction
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prediction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
