# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test_build:
    jobs:
      - build
      - build_docker
jobs:
  build:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  make install
                  # Install hadolint
                  wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                  chmod +x /bin/hadolint
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    # run lint!
    - run:
        name: run lint
        command: |
                  . venv/bin/activate
                  make lint

  build_docker:
    docker:
    # Use the same Docker base as the project
    - image: docker

    working_directory: ~/repo

    steps:
    - checkout
    - setup_remote_docker

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    # run login
    - run:
          name: docker login
          command: echo "$DOCKER_TOKEN" | docker login -u adrik976 --password-stdin
    
    # run build
    - run:
        name: Build Docker image
        command: docker build --tag adrik976/udacity-prediction:latest .

    # Push Docker image
    - run:
        name: Push to DockerHub
        command: |
            docker push adrik976/udacity-prediction:latest